### ISSUE TITLE
Error:(406, 28) error: cannot access StickyListHeadersListView class file for se.emilsjolander.stickylistheaders.StickyListHeadersListView not found

### ISSUE THREAD

**Issue by Priyanka-Mohanty** [joielechong/AgendaCalendarView#1]
getting error , when import this module to another project.
Error:(406, 28) error: cannot access StickyListHeadersListView
class file for se.emilsjolander.stickylistheaders.StickyListHeadersListView not found

warning: unknown enum constant ThreadMode.MAIN
  reason: class file for org.greenrobot.eventbus.ThreadMode not found
warning: unknown enum constant ThreadMode.MAIN

**Comment by joielechong** [comment]
This is a major bug which is already solved in the current commit. Please be noted that this project is still in WIP.
